<?php 
function tpl_5453638e_content__r_sx7waig2kOq1om0tAT8w(PHPTAL $tpl, PHPTAL_Context $ctx) {
	$_thistpl = $tpl ;
	/* tag "documentElement" from line 1 */ ;
?>
<!-- BEGINING Content -->
<?php 	/* tag "h1" from line 2 */; ?>
<h1>Separated content test</h1>
<!-- END Content --><?php 
	/* end */ ;

}

?>
<?php /* 
*** DO NOT EDIT THIS FILE ***

Generated by PHPTAL from C:\www\my\github\FatFree-PHPTAL\test\view\content.html (edit that file instead) */; ?>