<?php 
function tpl_54523fb3_valid__woaaRfTLSp1_VPfmRScysg(PHPTAL $tpl, PHPTAL_Context $ctx) {
	$_thistpl = $tpl ;
	/* tag "documentElement" from line 1 */ ;
	/* tag "html" from line 1 */ ;
?>
<html>
    <?php 	/* tag "header" from line 2 */; ?>
<header></header>
<?php 	/* tag "body" from line 3 */; ?>
<body>
<?php 	/* tag "h1" from line 4 */; ?>
<h1>View test</h1>
<?php 	/* tag "h2" from line 5 */; ?>
<h2><?php echo phptal_escape($ctx->var1, 'UTF-8') ?>
</h2>
</body>
</html><?php 
	/* end */ ;

}

?>
<?php /* 
*** DO NOT EDIT THIS FILE ***

Generated by PHPTAL from C:\www\my\github\FatFree-PHPTAL\test\view\valid.html (edit that file instead) */; ?>