<?php 
function tpl_545379db_content__uOfMe40_TT1RgAxuPTvsEQ(PHPTAL $tpl, PHPTAL_Context $ctx) {
	$_thistpl = $tpl ;
	/* tag "documentElement" from line 1 */ ;
	/* tag "html" from line 1 */ ;
?>
<html>
    <?php 	/* tag "header" from line 2 */; ?>
<header>Header</header>
<?php 	/* tag "body" from line 3 */; ?>
<body>
<!-- END Header --><!-- BEGINING Content -->
<?php 	/* tag "h1" from line 5 */; ?>
<h1>Separated content test</h1>
<!-- END Content -->
<!-- BEGINNING Footer -->
</body>
</html><?php 
	/* end */ ;

}

?>
<?php /* 
*** DO NOT EDIT THIS FILE ***

Generated by PHPTAL from C:\www\my\github\FatFree-PHPTAL\test\view\content.html (edit that file instead) */; ?>